### PR TITLE
Add Solaris gdiff support

### PR DESCRIPTION
**Pull request by rbrunckhorst**

### CODE REVIEW

**Review by CheyenneWills — COMMENTED** [review]
It appears that gdiff is not generally available on some platforms ('yum provides gdiff' doesn't list any available RPMs).

**Comment by rbrunckhorst** [comment]
> It appears that gdiff is not generally available on some platforms ('yum provides gdiff' on a centos7 system doesn't list any available RPMs).

Thank you for looking into this. This was just a type, it should be /usr/bin/diff. On linux diff is already a gnu based diff which supports --recursive as option.

**Comment by meffie** [comment]
On Mon, 31 Jan 2022 07:41:49 -0800
Cheyenne Wills ***@***.***> wrote:

> @CheyenneWills commented on this pull request.
> 
> It appears that gdiff is not generally available on some platforms ('yum provides gdiff' doesn't list any available RPMs).

On RPM-based platforms, GNU diff is just 'diff'.

-- 
Michael Meffie ***@***.***>

**Review by CheyenneWills — COMMENTED** [review]
Looks fine with change

**Comment by meffie** [comment]
Thanks Ralf. I squash and merged this. 

commit 2f54c625d82b30e530df4153ca607cd3acf59f09 (HEAD -> master, origin/master, origin/HEAD, fix-compare-files-on-solaris)
Author: Ralf Brunckhorst <rbrunckhorst@sinenomine.net>
Date:   Sun Jan 30 11:12:09 2022 +0100

I think in the future we should implement the "Compare Files" keyword in the keyword library (in python), but we can use gdiff for now.

**Pull request closed without merging**
